Repository ArneBinder/pie-modules, pull requests merged in 2025-02, with the labels that each got.

#152 add `argument_type_whitelist` parameter to `RETextClassificationWithIndicesTaskModule`
  src/pie_modules/taskmodules/re_text_classification_with_indices.py
  tests/taskmodules/test_re_text_classification_with_indices.py
Labels: enhancement

#156 CI: define only major version for all actions from Github
  .github/workflows/code-quality-main.yaml
  .github/workflows/code-quality-pr.yaml
  .github/workflows/labeler.yml
  .github/workflows/release.yml
  .github/workflows/test.yaml
Labels: bug, ci

#155 add `handle_relations_with_same_arguments` parameter to `RETextClassificationWithIndicesTaskModule`
  src/pie_modules/taskmodules/re_text_classification_with_indices.py
  tests/taskmodules/test_re_text_classification_with_indices.py
Labels: enhancement, breaking
